---

- hosts: pg
  roles:
  - role: soplakanets.hosts
    save_hosts:
    - name: pg1
      ip: 172.12.16.101
    - name: pg2
      ip: 172.12.16.102
    - name: bdr1
      ip: 172.12.17.101
    - name: bdr2
      ip: 172.12.17.102

  - role: jpic.pacman
    pacman_mirrors:
    - http://arch.yourlabs.org/

  - role: franklinkim.openssl
    sudo: yes
    openssl_self_signed:
    - name: postgres
      country: FR
      state: IDF
      city: Paris
      organization: postgres
      unit: postgres
      email: postgres@localhost
      days: 3650

  - role: .
    pg_bdr_git_src: /vagrant/_bdr
    pg_ips:
      bdr1: 172.12.17.101
      bdr2: 172.12.17.102
    pg_ssl: 'on'
    pg_ssl_cert_file: /etc/ssl/certs/postgres.crt
    pg_ssl_ca_file: /etc/ssl/certs/postgres.crt
    pg_ssl_key_file: /etc/ssl/private/postgres.key
    pg_users:
    - name: testuser
      pass: testpass
    pg_databases:
    - name: testdb
    pg_privileges:
    - user: testuser
      db: testdb
      priv: all
    pg_replication:
    - name: bdr1testdb
      auth_method: trust
      dsn:
        dbname: testdb 
        user: postgres 
        host: bdr1
      master_for:
      - host: bdr2
        local_dsn:
          dbname: testdb
          user: postgres
    - name: bdr2testdb
      auth_method: trust
      dsn:
        dbname: testdb 
        user: postgres 
        host: bdr2
