---

- hosts: localhost
  connection: local
  tasks:
  - shell: git clone git://git.postgresql.org/git/2ndquadrant_bdr.git _bdr
    ignore_errors: yes
  - shell: git checkout -b bdr-pg/REL9_4_STABLE origin/bdr-pg/REL9_4_STABLE chdir=_bdr
    ignore_errors: yes
  - shell: git checkout -b bdr-plugin/stable origin/bdr-plugin/stable  chdir=_bdr
    ignore_errors: yes

- hosts: pg
  roles:
  - role: soplakanets.hosts
    save_hosts:
    - name: pg1
      ip: 172.16.16.101
    - name: pg2
      ip: 172.16.16.102
    - name: bdr1
      ip: 172.16.17.101
    - name: bdr2
      ip: 172.16.17.102

  - role: jpic.pacman
    pacman_mirrors:
    - http://arch.yourlabs.org/

  - role: franklinkim.openssl
    sudo: yes
    openssl_self_signed:
    - name: postgres
      country: FR
      state: IDF
      city: Paris
      organization: postgres
      unit: postgres
      email: postgres@localhost
      days: 3650

  - role: .
    pg_bdr_git_src: /vagrant/_bdr
    pg_ips:
      bdr1: 172.16.17.101
      bdr2: 172.16.17.102
    pg_ssl: 'on'
    pg_ssl_cert_file: /etc/ssl/certs/postgres.crt
    pg_ssl_ca_file: /etc/ssl/certs/postgres.crt
    pg_ssl_key_file: /etc/ssl/private/postgres.key
    pg_users:
    - name: testuser
      pass: testpass
    - name: replicator
      pass: mypass
      role_attr_flags: REPLICATION,LOGIN,SUPERUSER
    pg_databases:
    - name: dbx
    pg_privileges:
    - user: testuser
      db: dbx
    pg_replication:
    - name: bdr1dbx
      auth_method: md5
      dsn:
        dbname: dbx 
        user: replicator
        host: bdr1
        sslmode: require
      master_for:
      - host: bdr2
        local_dsn:
          dbname: dbx
          user: postgres
    - name: bdr2dbx
      auth_method: md5
      dsn:
        dbname: dbx 
        user: replicator
        host: bdr2
        sslmode: require
