---
- hosts: pg
  roles:
  - role: jpic.pacman
    pacman_mirrors:
    - http://arch.yourlabs.org/

  - role: .
    pg_ssl: 'on'
    pg_ssl_cert_path: server.crt
    pg_ssl_key_path: server.key
    pg_users:
    - name: testuser
      pass: testpass
    pg_databases:
    - name: testdb
    pg_privileges:
    - user: testuser
      db: testdb
      priv: all
