---

- name: setup conf files
  sudo: yes
  template:
    src: '{{ item }}'
    dest: '{{ pg_data }}/{{ item }}'
    owner: '{{ pg_user }}'
    group: '{{ pg_group }}'
    mode: 0700
  with_items:
  - postgresql.conf
  - pg_hba.conf
  - pg_ident.conf
  notify: pg reload
