---

- name: secure ssl certificates
  sudo: yes
  file: 
    path: '{{ item }}' 
    owner: '{{ pg_user }}'
    group: '{{ pg_group }}'
    mode: 0600
  with_items:
  - '{{ pg_ssl_cert_file }}'
  - '{{ pg_ssl_key_file }}'
  - '{{ pg_ssl_ca_file }}'
  notify: pg restart

- name: setup conf files
  sudo: yes
  template:
    src: '{{ item }}'
    dest: '{{ pg_data }}/{{ item }}'
    owner: '{{ pg_user }}'
    group: '{{ pg_group }}'
    mode: 0700
  with_items:
  - postgresql.conf
  - pg_hba.conf
  - pg_ident.conf
  notify: pg reload
