---

# requirement: pacman repo `yourlabs` on `arch.yourlabs.org/$repo/os/$arch`
- pacman: name=polkit,postgresql-bdr-git,postgresql-bdr-extensions-git,python2-pip
  sudo: yes

- pip:
    executable: pip2
    name: psycopg2
  sudo: yes
  register: pg_pip

- shell: chmod -R 755 /usr/lib/python2.7/site-packages
  when: pg_pip.changed
  sudo: yes
