---


- pg_bdr_connections: 
    pg_replications: '{{ pg_replication }}'
    pg_dbclients: '{{ pg_dbclients }}'
    pg_ips: '{{ pg_ips }}'
    for_host: '{{ ansible_hostname }}'
  register: pg_bdr_connections

# Let's define the kind of setup we are doing
- set_fact: pg_type=master
  when: ansible_hostname == pg_master and not pg_bdr_path

- set_fact: pg_type=slave
  when: not ansible_hostname == pg_master and not pg_bdr_path

- set_fact: pg_type=bdr
  when: pg_bdr_path != False

# Ensure the postgresql user exists
- include: user.yml

# Install bdr from source or simple postgresql package
- include: install.yml
  when: pg_type != 'bdr'

- include: build_bdr.yml
  when: pg_type == 'bdr' and pg_bdr_build

- include: install_bdr.yml
  when: pg_type == 'bdr' and not pg_bdr_build

# Ensure the datadir exists
- include: initdb.yml

- include: configure.yml

# Setup replication
- include: replication.yml
  when: pg_type != 'bdr'

- meta: flush_handlers

- include: admin.yml
  when: pg_type != 'slave'
